<?php

return [
    'anime' => [
        [
            'id' => 1,
            'slug' => 'solo-leveling',
            'title' => 'Solo Leveling',
            'japanese_title' => '俺だけレベルアップな件',
            'poster' => 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.8,
            'year' => 2024,
            'type' => 'TV',
            'episodes' => 12,
            'status' => 'Ongoing',
            'genres' => ['Action', 'Fantasy', 'Adventure'],
            'synopsis' => 'In a world where hunters, humans who possess magical abilities, must battle deadly monsters to protect mankind from certain annihilation, a notoriously weak hunter named Sung Jinwoo finds himself in a seamless struggle for survival.',
            'trending_rank' => 1,
            'latest_ep' => 'EP 12',
            'latest_date' => '1 hour ago',
            'schedule_day' => 'SAT',
            'schedule_time' => '23:30',
            'continue_progress' => 78,
            'continue_ep' => 12,
            'studio' => 'A-1 Pictures',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: " . [
                        1 => 'I\'m Used to It',
                        2 => 'If I Had One More Chance',
                        3 => 'It\'s Like a Game',
                        4 => 'I\'ve Gotta Get Stronger',
                        5 => 'A Pretty Good Deal',
                        6 => 'The Real Hunt Begins',
                        7 => 'Let\'s See How Far I Can Go',
                        8 => 'This Is Frustrating',
                        9 => 'You\'ve Been Hiding Your Skills',
                        10 => 'What Is This, a Quest?',
                        11 => 'A Knight Who Defends an Empty Throne',
                        12 => 'Arise'
                    ][$i],
                    'duration' => '24 min',
                    'watched' => $i < 12,
                    'thumbnail' => 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 2,
            'slug' => 'one-piece',
            'title' => 'One Piece',
            'japanese_title' => 'ワンピース',
            'poster' => 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.2,
            'year' => 1999,
            'type' => 'TV',
            'episodes' => 1142,
            'status' => 'Ongoing',
            'genres' => ['Action', 'Adventure', 'Comedy', 'Fantasy', 'Shounen'],
            'synopsis' => 'Monkey D. Luffy sets off on an epic journey with his pirate crew across the Grand Line in search of the legendary ultimate treasure known as "One Piece" to become the Pirate King.',
            'trending_rank' => 2,
            'latest_ep' => 'EP 1142',
            'latest_date' => '3 hours ago',
            'schedule_day' => 'SUN',
            'schedule_time' => '09:30',
            'continue_progress' => 45,
            'continue_ep' => 1141,
            'studio' => 'Toei Animation',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                $epNum = 1142 - 12 + $i;
                return [
                    'number' => $epNum,
                    'title' => "Episode $epNum: Clash of the Emperors in Egghead",
                    'duration' => '24 min',
                    'watched' => $i < 12,
                    'thumbnail' => 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 3,
            'slug' => 'jujutsu-kaisen',
            'title' => 'Jujutsu Kaisen',
            'japanese_title' => '呪術廻戦',
            'poster' => 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.5,
            'year' => 2023,
            'type' => 'TV',
            'episodes' => 47,
            'status' => 'Completed',
            'genres' => ['Action', 'Supernatural', 'School', 'Shounen', 'Dark Fantasy'],
            'synopsis' => 'A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman\'s school to be able to locate the demon\'s other body parts and thus exorcise himself.',
            'trending_rank' => 3,
            'latest_ep' => 'EP 24',
            'latest_date' => 'Yesterday',
            'schedule_day' => 'THU',
            'schedule_time' => '23:56',
            'continue_progress' => 90,
            'continue_ep' => 23,
            'studio' => 'MAPPA',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: Shibuya Incident Arc",
                    'duration' => '24 min',
                    'watched' => true,
                    'thumbnail' => 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 4,
            'slug' => 'demon-slayer',
            'title' => 'Demon Slayer: Kimetsu no Yaiba',
            'japanese_title' => '鬼滅の刃',
            'poster' => 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.6,
            'year' => 2024,
            'type' => 'TV',
            'episodes' => 55,
            'status' => 'Completed',
            'genres' => ['Action', 'Fantasy', 'Historical', 'Shounen'],
            'synopsis' => 'Tanjiro Kamado, a young boy whose family was slaughtered by demons, vows to become a Demon Slayer to cure his sister Nezuko and turn her back into a human.',
            'trending_rank' => 4,
            'latest_ep' => 'EP 8',
            'latest_date' => '2 days ago',
            'schedule_day' => 'SUN',
            'schedule_time' => '23:15',
            'continue_progress' => 30,
            'continue_ep' => 5,
            'studio' => 'ufotable',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: Hashira Training Arc",
                    'duration' => '25 min',
                    'watched' => false,
                    'thumbnail' => 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 8))
        ],
        [
            'id' => 5,
            'slug' => 'frieren',
            'title' => 'Frieren: Beyond Journey\'s End',
            'japanese_title' => '葬送のフリーレン',
            'poster' => 'https://images.unsplash.com/photo-1514539079130-25950c84af65?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.9,
            'year' => 2024,
            'type' => 'TV',
            'episodes' => 28,
            'status' => 'Completed',
            'genres' => ['Adventure', 'Drama', 'Fantasy', 'Slice of Life'],
            'synopsis' => 'An elf mage and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. But Frieren will long outlive the rest of her former party. How will she come to understand what life means to the humans around her?',
            'trending_rank' => 5,
            'latest_ep' => 'EP 28',
            'latest_date' => '3 days ago',
            'schedule_day' => 'FRI',
            'schedule_time' => '23:00',
            'continue_progress' => 60,
            'continue_ep' => 18,
            'studio' => 'Madhouse',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: The Journey Continues North",
                    'duration' => '24 min',
                    'watched' => true,
                    'thumbnail' => 'https://images.unsplash.com/photo-1514539079130-25950c84af65?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 6,
            'slug' => 'attack-on-titan',
            'title' => 'Attack on Titan',
            'japanese_title' => '進撃の巨人',
            'poster' => 'https://images.unsplash.com/photo-1560972550-aba3456b5564?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.7,
            'year' => 2023,
            'type' => 'TV',
            'episodes' => 89,
            'status' => 'Completed',
            'genres' => ['Action', 'Dark Fantasy', 'Mystery', 'Seinen'],
            'synopsis' => 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
            'trending_rank' => null,
            'latest_ep' => 'EP 89',
            'latest_date' => 'Completed',
            'schedule_day' => 'MON',
            'schedule_time' => '00:00',
            'continue_progress' => 100,
            'continue_ep' => 89,
            'studio' => 'MAPPA / Wit Studio',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: The Rumbling Awakens",
                    'duration' => '26 min',
                    'watched' => true,
                    'thumbnail' => 'https://images.unsplash.com/photo-1560972550-aba3456b5564?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 7,
            'slug' => 'bleach-thousand-year-blood-war',
            'title' => 'Bleach: Thousand-Year Blood War',
            'japanese_title' => 'BLEACH 千年血戦篇',
            'poster' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.4,
            'year' => 2024,
            'type' => 'TV',
            'episodes' => 39,
            'status' => 'Ongoing',
            'genres' => ['Action', 'Supernatural', 'Shounen'],
            'synopsis' => 'Substitute Soul Reaper Ichigo Kurosaki enters the fray as the Quincy army, led by Yhwach, declares war against the Soul Society.',
            'trending_rank' => null,
            'latest_ep' => 'EP 26',
            'latest_date' => '4 days ago',
            'schedule_day' => 'SAT',
            'schedule_time' => '23:00',
            'continue_progress' => 0,
            'continue_ep' => 1,
            'studio' => 'Studio Pierrot',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: The Blood Warfare",
                    'duration' => '24 min',
                    'watched' => false,
                    'thumbnail' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 8,
            'slug' => 'naruto-shippuden',
            'title' => 'Naruto Shippuden',
            'japanese_title' => 'ナルト 疾風伝',
            'poster' => 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.0,
            'year' => 2007,
            'type' => 'TV',
            'episodes' => 500,
            'status' => 'Completed',
            'genres' => ['Action', 'Adventure', 'Martial Arts', 'Shounen'],
            'synopsis' => 'Naruto Uzumaki returns to the Hidden Leaf Village older and stronger after two and a half years of training with Jiraiya, ready to face the Akatsuki organization.',
            'trending_rank' => null,
            'latest_ep' => 'EP 500',
            'latest_date' => 'Classic',
            'schedule_day' => 'TUE',
            'schedule_time' => '18:00',
            'continue_progress' => 15,
            'continue_ep' => 167,
            'studio' => 'Studio Pierrot',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: Homecoming",
                    'duration' => '23 min',
                    'watched' => true,
                    'thumbnail' => 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 9,
            'slug' => 'my-hero-academia',
            'title' => 'My Hero Academia Season 7',
            'japanese_title' => '僕のヒーローアカデミア',
            'poster' => 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
            'rating' => 8.8,
            'year' => 2024,
            'type' => 'TV',
            'episodes' => 21,
            'status' => 'Ongoing',
            'genres' => ['Action', 'School', 'Super Power', 'Shounen'],
            'synopsis' => 'The ultimate battle between the heroes and All For One\'s villain coalition erupts as Izuku Midoriya fights for the future of society.',
            'trending_rank' => null,
            'latest_ep' => 'EP 19',
            'latest_date' => '5 days ago',
            'schedule_day' => 'SAT',
            'schedule_time' => '17:30',
            'continue_progress' => 0,
            'continue_ep' => 1,
            'studio' => 'Bones',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: Division & Clash",
                    'duration' => '24 min',
                    'watched' => false,
                    'thumbnail' => 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 10,
            'slug' => 'one-punch-man',
            'title' => 'One Punch Man',
            'japanese_title' => 'ワンパンマン',
            'poster' => 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.1,
            'year' => 2015,
            'type' => 'TV',
            'episodes' => 24,
            'status' => 'Completed',
            'genres' => ['Action', 'Comedy', 'Parody', 'Super Power', 'Sci-Fi'],
            'synopsis' => 'Saitama is a hero who can defeat any opponent with a single punch, but suffers from existential boredom because nothing challenges him.',
            'trending_rank' => null,
            'latest_ep' => 'EP 24',
            'latest_date' => 'Classic',
            'schedule_day' => 'WED',
            'schedule_time' => '21:00',
            'continue_progress' => 50,
            'continue_ep' => 12,
            'studio' => 'Madhouse / J.C.Staff',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: The Strongest Man",
                    'duration' => '24 min',
                    'watched' => true,
                    'thumbnail' => 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 11,
            'slug' => 'hunter-x-hunter',
            'title' => 'Hunter x Hunter',
            'japanese_title' => 'ハンター×ハンター',
            'poster' => 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1600&auto=format&fit=crop',
            'rating' => 9.7,
            'year' => 2011,
            'type' => 'TV',
            'episodes' => 148,
            'status' => 'Completed',
            'genres' => ['Action', 'Adventure', 'Fantasy', 'Shounen'],
            'synopsis' => 'Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness, to find his father who abandoned him when he was young.',
            'trending_rank' => null,
            'latest_ep' => 'EP 148',
            'latest_date' => 'Classic',
            'schedule_day' => 'THU',
            'schedule_time' => '20:00',
            'continue_progress' => 0,
            'continue_ep' => 1,
            'studio' => 'Madhouse',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: Departure × And × Friends",
                    'duration' => '24 min',
                    'watched' => false,
                    'thumbnail' => 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
        [
            'id' => 12,
            'slug' => 'black-clover',
            'title' => 'Black Clover',
            'japanese_title' => 'ブラッククローバー',
            'poster' => 'https://images.unsplash.com/photo-1514539079130-25950c84af65?q=80&w=800&auto=format&fit=crop',
            'banner' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop',
            'rating' => 8.9,
            'year' => 2017,
            'type' => 'TV',
            'episodes' => 170,
            'status' => 'Completed',
            'genres' => ['Action', 'Comedy', 'Fantasy', 'Shounen', 'Magic'],
            'synopsis' => 'Asta and Yuno were abandoned at the same church on the same day. Raised together as children, they came to know about the Wizard King and vowed that they would compete against each other for the position.',
            'trending_rank' => null,
            'latest_ep' => 'EP 170',
            'latest_date' => 'Classic',
            'schedule_day' => 'TUE',
            'schedule_time' => '18:25',
            'continue_progress' => 0,
            'continue_ep' => 1,
            'studio' => 'Studio Pierrot',
            'quality' => 'HD',
            'sub' => true,
            'dub' => true,
            'episodes_list' => array_map(function($i) {
                return [
                    'number' => $i,
                    'title' => "Episode $i: Asta and Yuno",
                    'duration' => '24 min',
                    'watched' => false,
                    'thumbnail' => 'https://images.unsplash.com/photo-1514539079130-25950c84af65?q=80&w=600&auto=format&fit=crop'
                ];
            }, range(1, 12))
        ],
    ],
    'genres' => [
        'Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Romance',
        'School', 'Shounen', 'Seinen', 'Isekai', 'Horror', 'Mystery',
        'Sci-Fi', 'Sports', 'Slice of Life'
    ],
    'schedule_days' => ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']
];
